import { DeliveryDriver, DeliveryTracking } from '@/types/logistics';

// Helper to get a date N days ago
const getDaysAgo = (days: number): Date => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

export const mockDrivers: DeliveryDriver[] = [
  {
    id: 'driver-1',
    name: 'Ramesh Yadav',
    phone: '+91 9876543401',
    vehicleNumber: 'KA-01-AB-1234',
    vehicleType: 'truck',
    rating: 4.8,
  },
  {
    id: 'driver-2',
    name: 'Sunil Kumar',
    phone: '+91 9876543402',
    vehicleNumber: 'MH-12-CD-5678',
    vehicleType: 'mini-truck',
    rating: 4.5,
  },
  {
    id: 'driver-3',
    name: 'Prakash Singh',
    phone: '+91 9876543403',
    vehicleNumber: 'DL-08-EF-9012',
    vehicleType: 'pickup',
    rating: 4.9,
  },
  {
    id: 'driver-4',
    name: 'Vijay Sharma',
    phone: '+91 9876543404',
    vehicleNumber: 'TN-07-GH-3456',
    vehicleType: 'truck',
    rating: 4.6,
  },
];

// Bengaluru area coordinates
const bengaluruLocations = {
  koramangala: { lat: 12.9352, lng: 77.6245 },
  whitefield: { lat: 12.9698, lng: 77.7500 },
  electronicCity: { lat: 12.8399, lng: 77.6770 },
  yeshwanthpur: { lat: 13.0280, lng: 77.5430 },
  jayanagar: { lat: 12.9308, lng: 77.5838 },
  malleshwaram: { lat: 13.0035, lng: 77.5647 },
  hebbal: { lat: 13.0358, lng: 77.5970 },
  btmLayout: { lat: 12.9166, lng: 77.6101 },
};

const getETA = (hoursFromNow: number) => {
  const date = new Date();
  date.setHours(date.getHours() + hoursFromNow);
  return date;
};

// Calculate a point between origin and destination based on progress
const interpolateLocation = (
  origin: { lat: number; lng: number },
  destination: { lat: number; lng: number },
  progress: number
) => {
  return {
    lat: origin.lat + (destination.lat - origin.lat) * progress,
    lng: origin.lng + (destination.lng - origin.lng) * progress,
  };
};

export const mockDeliveries: DeliveryTracking[] = [
  // Active deliveries
  {
    id: 'delivery-1',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[0],
    status: 'in_transit',
    origin: {
      address: 'Village Rampur, Punjab',
      ...bengaluruLocations.yeshwanthpur,
    },
    destination: {
      address: 'Yeshwanthpur Market, Bangalore',
      ...bengaluruLocations.koramangala,
    },
    currentLocation: interpolateLocation(
      bengaluruLocations.yeshwanthpur,
      bengaluruLocations.koramangala,
      0.6
    ),
    estimatedArrival: getETA(2),
    produceName: 'Tomatoes',
    quantity: 500,
    sellerName: 'Rajesh Kumar',
    buyerName: 'Vikram Mehta',
    createdAt: new Date(),
  },
  {
    id: 'delivery-2',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[1],
    status: 'picked_up',
    origin: {
      address: 'Village Kolhapur, Maharashtra',
      ...bengaluruLocations.hebbal,
    },
    destination: {
      address: 'Market Yard, Pune',
      ...bengaluruLocations.electronicCity,
    },
    currentLocation: interpolateLocation(
      bengaluruLocations.hebbal,
      bengaluruLocations.electronicCity,
      0.2
    ),
    estimatedArrival: getETA(4),
    produceName: 'Onions',
    quantity: 1000,
    sellerName: 'Suresh Patil',
    buyerName: 'Sneha Joshi',
    createdAt: new Date(),
  },
  {
    id: 'delivery-3',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[2],
    status: 'in_transit',
    origin: {
      address: 'Village Warangal, Telangana',
      ...bengaluruLocations.whitefield,
    },
    destination: {
      address: 'Rythu Bazaar, Hyderabad',
      ...bengaluruLocations.jayanagar,
    },
    currentLocation: interpolateLocation(
      bengaluruLocations.whitefield,
      bengaluruLocations.jayanagar,
      0.75
    ),
    estimatedArrival: getETA(1),
    produceName: 'Potatoes',
    quantity: 2000,
    sellerName: 'Ganesh Reddy',
    buyerName: 'Kavita Rao',
    createdAt: new Date(),
  },
  {
    id: 'delivery-4',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[3],
    status: 'pending',
    origin: {
      address: 'Village Meerut, Uttar Pradesh',
      ...bengaluruLocations.malleshwaram,
    },
    destination: {
      address: 'Subzi Mandi, Kolkata',
      ...bengaluruLocations.btmLayout,
    },
    currentLocation: bengaluruLocations.malleshwaram,
    estimatedArrival: getETA(6),
    produceName: 'Carrots',
    quantity: 800,
    sellerName: 'Anil Singh',
    buyerName: 'Sanjay Verma',
    createdAt: new Date(),
  },
  // Completed deliveries - Last month (logistics-1: 5, logistics-2: 3)
  {
    id: 'delivery-5',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[0],
    status: 'delivered',
    origin: { address: 'Farm A, Karnataka', ...bengaluruLocations.hebbal },
    destination: { address: 'Market B, Bangalore', ...bengaluruLocations.koramangala },
    currentLocation: bengaluruLocations.koramangala,
    estimatedArrival: getDaysAgo(5),
    deliveredAt: getDaysAgo(5),
    produceName: 'Tomatoes',
    quantity: 300,
    sellerName: 'Farmer A',
    buyerName: 'Buyer B',
    createdAt: getDaysAgo(6),
  },
  {
    id: 'delivery-6',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[1],
    status: 'delivered',
    origin: { address: 'Farm C, Tamil Nadu', ...bengaluruLocations.whitefield },
    destination: { address: 'Market D, Chennai', ...bengaluruLocations.electronicCity },
    currentLocation: bengaluruLocations.electronicCity,
    estimatedArrival: getDaysAgo(10),
    deliveredAt: getDaysAgo(10),
    produceName: 'Onions',
    quantity: 600,
    sellerName: 'Farmer C',
    buyerName: 'Buyer D',
    createdAt: getDaysAgo(11),
  },
  {
    id: 'delivery-7',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[2],
    status: 'delivered',
    origin: { address: 'Farm E, Maharashtra', ...bengaluruLocations.malleshwaram },
    destination: { address: 'Market F, Pune', ...bengaluruLocations.btmLayout },
    currentLocation: bengaluruLocations.btmLayout,
    estimatedArrival: getDaysAgo(15),
    deliveredAt: getDaysAgo(15),
    produceName: 'Potatoes',
    quantity: 800,
    sellerName: 'Farmer E',
    buyerName: 'Buyer F',
    createdAt: getDaysAgo(16),
  },
  {
    id: 'delivery-8',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[3],
    status: 'delivered',
    origin: { address: 'Farm G, Andhra Pradesh', ...bengaluruLocations.jayanagar },
    destination: { address: 'Market H, Hyderabad', ...bengaluruLocations.yeshwanthpur },
    currentLocation: bengaluruLocations.yeshwanthpur,
    estimatedArrival: getDaysAgo(20),
    deliveredAt: getDaysAgo(20),
    produceName: 'Carrots',
    quantity: 400,
    sellerName: 'Farmer G',
    buyerName: 'Buyer H',
    createdAt: getDaysAgo(21),
  },
  {
    id: 'delivery-9',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[0],
    status: 'delivered',
    origin: { address: 'Farm I, Gujarat', ...bengaluruLocations.koramangala },
    destination: { address: 'Market J, Ahmedabad', ...bengaluruLocations.hebbal },
    currentLocation: bengaluruLocations.hebbal,
    estimatedArrival: getDaysAgo(25),
    deliveredAt: getDaysAgo(25),
    produceName: 'Cauliflower',
    quantity: 500,
    sellerName: 'Farmer I',
    buyerName: 'Buyer J',
    createdAt: getDaysAgo(26),
  },
  {
    id: 'delivery-10',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[1],
    status: 'delivered',
    origin: { address: 'Farm K, Rajasthan', ...bengaluruLocations.electronicCity },
    destination: { address: 'Market L, Jaipur', ...bengaluruLocations.whitefield },
    currentLocation: bengaluruLocations.whitefield,
    estimatedArrival: getDaysAgo(28),
    deliveredAt: getDaysAgo(28),
    produceName: 'Cabbage',
    quantity: 350,
    sellerName: 'Farmer K',
    buyerName: 'Buyer L',
    createdAt: getDaysAgo(29),
  },
  {
    id: 'delivery-11',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[2],
    status: 'delivered',
    origin: { address: 'Farm M, Kerala', ...bengaluruLocations.btmLayout },
    destination: { address: 'Market N, Kochi', ...bengaluruLocations.malleshwaram },
    currentLocation: bengaluruLocations.malleshwaram,
    estimatedArrival: getDaysAgo(30),
    deliveredAt: getDaysAgo(30),
    produceName: 'Banana',
    quantity: 700,
    sellerName: 'Farmer M',
    buyerName: 'Buyer N',
    createdAt: getDaysAgo(31),
  },
  {
    id: 'delivery-12',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[3],
    status: 'delivered',
    origin: { address: 'Farm O, Punjab', ...bengaluruLocations.yeshwanthpur },
    destination: { address: 'Market P, Ludhiana', ...bengaluruLocations.jayanagar },
    currentLocation: bengaluruLocations.jayanagar,
    estimatedArrival: getDaysAgo(30),
    deliveredAt: getDaysAgo(30),
    produceName: 'Wheat',
    quantity: 1000,
    sellerName: 'Farmer O',
    buyerName: 'Buyer P',
    createdAt: getDaysAgo(31),
  },
  // Completed deliveries - 2-6 months ago (logistics-1: 8, logistics-2: 6)
  {
    id: 'delivery-13',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[0],
    status: 'delivered',
    origin: { address: 'Farm Q, UP', ...bengaluruLocations.hebbal },
    destination: { address: 'Market R, Lucknow', ...bengaluruLocations.koramangala },
    currentLocation: bengaluruLocations.koramangala,
    estimatedArrival: getDaysAgo(45),
    deliveredAt: getDaysAgo(45),
    produceName: 'Rice',
    quantity: 2000,
    sellerName: 'Farmer Q',
    buyerName: 'Buyer R',
    createdAt: getDaysAgo(46),
  },
  {
    id: 'delivery-14',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[1],
    status: 'delivered',
    origin: { address: 'Farm S, Bihar', ...bengaluruLocations.whitefield },
    destination: { address: 'Market T, Patna', ...bengaluruLocations.electronicCity },
    currentLocation: bengaluruLocations.electronicCity,
    estimatedArrival: getDaysAgo(60),
    deliveredAt: getDaysAgo(60),
    produceName: 'Maize',
    quantity: 1500,
    sellerName: 'Farmer S',
    buyerName: 'Buyer T',
    createdAt: getDaysAgo(61),
  },
  {
    id: 'delivery-15',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[2],
    status: 'delivered',
    origin: { address: 'Farm U, MP', ...bengaluruLocations.malleshwaram },
    destination: { address: 'Market V, Bhopal', ...bengaluruLocations.btmLayout },
    currentLocation: bengaluruLocations.btmLayout,
    estimatedArrival: getDaysAgo(75),
    deliveredAt: getDaysAgo(75),
    produceName: 'Soybean',
    quantity: 1200,
    sellerName: 'Farmer U',
    buyerName: 'Buyer V',
    createdAt: getDaysAgo(76),
  },
  {
    id: 'delivery-16',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[3],
    status: 'delivered',
    origin: { address: 'Farm W, Odisha', ...bengaluruLocations.jayanagar },
    destination: { address: 'Market X, Bhubaneswar', ...bengaluruLocations.yeshwanthpur },
    currentLocation: bengaluruLocations.yeshwanthpur,
    estimatedArrival: getDaysAgo(90),
    deliveredAt: getDaysAgo(90),
    produceName: 'Groundnut',
    quantity: 800,
    sellerName: 'Farmer W',
    buyerName: 'Buyer X',
    createdAt: getDaysAgo(91),
  },
  {
    id: 'delivery-17',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[0],
    status: 'delivered',
    origin: { address: 'Farm Y, WB', ...bengaluruLocations.koramangala },
    destination: { address: 'Market Z, Kolkata', ...bengaluruLocations.hebbal },
    currentLocation: bengaluruLocations.hebbal,
    estimatedArrival: getDaysAgo(105),
    deliveredAt: getDaysAgo(105),
    produceName: 'Jute',
    quantity: 600,
    sellerName: 'Farmer Y',
    buyerName: 'Buyer Z',
    createdAt: getDaysAgo(106),
  },
  {
    id: 'delivery-18',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[1],
    status: 'delivered',
    origin: { address: 'Farm AA, Assam', ...bengaluruLocations.electronicCity },
    destination: { address: 'Market BB, Guwahati', ...bengaluruLocations.whitefield },
    currentLocation: bengaluruLocations.whitefield,
    estimatedArrival: getDaysAgo(120),
    deliveredAt: getDaysAgo(120),
    produceName: 'Tea',
    quantity: 400,
    sellerName: 'Farmer AA',
    buyerName: 'Buyer BB',
    createdAt: getDaysAgo(121),
  },
  {
    id: 'delivery-19',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[2],
    status: 'delivered',
    origin: { address: 'Farm CC, HP', ...bengaluruLocations.btmLayout },
    destination: { address: 'Market DD, Shimla', ...bengaluruLocations.malleshwaram },
    currentLocation: bengaluruLocations.malleshwaram,
    estimatedArrival: getDaysAgo(135),
    deliveredAt: getDaysAgo(135),
    produceName: 'Apple',
    quantity: 500,
    sellerName: 'Farmer CC',
    buyerName: 'Buyer DD',
    createdAt: getDaysAgo(136),
  },
  {
    id: 'delivery-20',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[3],
    status: 'delivered',
    origin: { address: 'Farm EE, J&K', ...bengaluruLocations.yeshwanthpur },
    destination: { address: 'Market FF, Srinagar', ...bengaluruLocations.jayanagar },
    currentLocation: bengaluruLocations.jayanagar,
    estimatedArrival: getDaysAgo(150),
    deliveredAt: getDaysAgo(150),
    produceName: 'Walnut',
    quantity: 300,
    sellerName: 'Farmer EE',
    buyerName: 'Buyer FF',
    createdAt: getDaysAgo(151),
  },
  {
    id: 'delivery-21',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[0],
    status: 'delivered',
    origin: { address: 'Farm GG, Uttarakhand', ...bengaluruLocations.hebbal },
    destination: { address: 'Market HH, Dehradun', ...bengaluruLocations.koramangala },
    currentLocation: bengaluruLocations.koramangala,
    estimatedArrival: getDaysAgo(165),
    deliveredAt: getDaysAgo(165),
    produceName: 'Litchi',
    quantity: 350,
    sellerName: 'Farmer GG',
    buyerName: 'Buyer HH',
    createdAt: getDaysAgo(166),
  },
  {
    id: 'delivery-22',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[1],
    status: 'delivered',
    origin: { address: 'Farm II, Jharkhand', ...bengaluruLocations.whitefield },
    destination: { address: 'Market JJ, Ranchi', ...bengaluruLocations.electronicCity },
    currentLocation: bengaluruLocations.electronicCity,
    estimatedArrival: getDaysAgo(180),
    deliveredAt: getDaysAgo(180),
    produceName: 'Mango',
    quantity: 450,
    sellerName: 'Farmer II',
    buyerName: 'Buyer JJ',
    createdAt: getDaysAgo(181),
  },
  {
    id: 'delivery-23',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[2],
    status: 'delivered',
    origin: { address: 'Farm KK, Chhattisgarh', ...bengaluruLocations.malleshwaram },
    destination: { address: 'Market LL, Raipur', ...bengaluruLocations.btmLayout },
    currentLocation: bengaluruLocations.btmLayout,
    estimatedArrival: getDaysAgo(180),
    deliveredAt: getDaysAgo(180),
    produceName: 'Paddy',
    quantity: 1800,
    sellerName: 'Farmer KK',
    buyerName: 'Buyer LL',
    createdAt: getDaysAgo(181),
  },
  // Completed deliveries - 7-12 months ago (logistics-1: 6, logistics-2: 5)
  {
    id: 'delivery-24',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[3],
    status: 'delivered',
    origin: { address: 'Farm MM, Goa', ...bengaluruLocations.jayanagar },
    destination: { address: 'Market NN, Panaji', ...bengaluruLocations.yeshwanthpur },
    currentLocation: bengaluruLocations.yeshwanthpur,
    estimatedArrival: getDaysAgo(210),
    deliveredAt: getDaysAgo(210),
    produceName: 'Cashew',
    quantity: 250,
    sellerName: 'Farmer MM',
    buyerName: 'Buyer NN',
    createdAt: getDaysAgo(211),
  },
  {
    id: 'delivery-25',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[0],
    status: 'delivered',
    origin: { address: 'Farm OO, Manipur', ...bengaluruLocations.koramangala },
    destination: { address: 'Market PP, Imphal', ...bengaluruLocations.hebbal },
    currentLocation: bengaluruLocations.hebbal,
    estimatedArrival: getDaysAgo(240),
    deliveredAt: getDaysAgo(240),
    produceName: 'Ginger',
    quantity: 400,
    sellerName: 'Farmer OO',
    buyerName: 'Buyer PP',
    createdAt: getDaysAgo(241),
  },
  {
    id: 'delivery-26',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[1],
    status: 'delivered',
    origin: { address: 'Farm QQ, Meghalaya', ...bengaluruLocations.electronicCity },
    destination: { address: 'Market RR, Shillong', ...bengaluruLocations.whitefield },
    currentLocation: bengaluruLocations.whitefield,
    estimatedArrival: getDaysAgo(270),
    deliveredAt: getDaysAgo(270),
    produceName: 'Turmeric',
    quantity: 350,
    sellerName: 'Farmer QQ',
    buyerName: 'Buyer RR',
    createdAt: getDaysAgo(271),
  },
  {
    id: 'delivery-27',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[2],
    status: 'delivered',
    origin: { address: 'Farm SS, Tripura', ...bengaluruLocations.btmLayout },
    destination: { address: 'Market TT, Agartala', ...bengaluruLocations.malleshwaram },
    currentLocation: bengaluruLocations.malleshwaram,
    estimatedArrival: getDaysAgo(300),
    deliveredAt: getDaysAgo(300),
    produceName: 'Pineapple',
    quantity: 600,
    sellerName: 'Farmer SS',
    buyerName: 'Buyer TT',
    createdAt: getDaysAgo(301),
  },
  {
    id: 'delivery-28',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[3],
    status: 'delivered',
    origin: { address: 'Farm UU, Mizoram', ...bengaluruLocations.yeshwanthpur },
    destination: { address: 'Market VV, Aizawl', ...bengaluruLocations.jayanagar },
    currentLocation: bengaluruLocations.jayanagar,
    estimatedArrival: getDaysAgo(330),
    deliveredAt: getDaysAgo(330),
    produceName: 'Orange',
    quantity: 450,
    sellerName: 'Farmer UU',
    buyerName: 'Buyer VV',
    createdAt: getDaysAgo(331),
  },
  {
    id: 'delivery-29',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[0],
    status: 'delivered',
    origin: { address: 'Farm WW, Nagaland', ...bengaluruLocations.hebbal },
    destination: { address: 'Market XX, Kohima', ...bengaluruLocations.koramangala },
    currentLocation: bengaluruLocations.koramangala,
    estimatedArrival: getDaysAgo(350),
    deliveredAt: getDaysAgo(350),
    produceName: 'Chilli',
    quantity: 200,
    sellerName: 'Farmer WW',
    buyerName: 'Buyer XX',
    createdAt: getDaysAgo(351),
  },
  {
    id: 'delivery-30',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[1],
    status: 'delivered',
    origin: { address: 'Farm YY, Arunachal', ...bengaluruLocations.whitefield },
    destination: { address: 'Market ZZ, Itanagar', ...bengaluruLocations.electronicCity },
    currentLocation: bengaluruLocations.electronicCity,
    estimatedArrival: getDaysAgo(360),
    deliveredAt: getDaysAgo(360),
    produceName: 'Kiwi',
    quantity: 150,
    sellerName: 'Farmer YY',
    buyerName: 'Buyer ZZ',
    createdAt: getDaysAgo(361),
  },
  {
    id: 'delivery-31',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[2],
    status: 'delivered',
    origin: { address: 'Farm AAA, Sikkim', ...bengaluruLocations.malleshwaram },
    destination: { address: 'Market BBB, Gangtok', ...bengaluruLocations.btmLayout },
    currentLocation: bengaluruLocations.btmLayout,
    estimatedArrival: getDaysAgo(365),
    deliveredAt: getDaysAgo(365),
    produceName: 'Cardamom',
    quantity: 100,
    sellerName: 'Farmer AAA',
    buyerName: 'Buyer BBB',
    createdAt: getDaysAgo(366),
  },
  {
    id: 'delivery-32',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[3],
    status: 'delivered',
    origin: { address: 'Farm CCC, Telangana', ...bengaluruLocations.jayanagar },
    destination: { address: 'Market DDD, Warangal', ...bengaluruLocations.yeshwanthpur },
    currentLocation: bengaluruLocations.yeshwanthpur,
    estimatedArrival: getDaysAgo(365),
    deliveredAt: getDaysAgo(365),
    produceName: 'Cotton',
    quantity: 900,
    sellerName: 'Farmer CCC',
    buyerName: 'Buyer DDD',
    createdAt: getDaysAgo(366),
  },
  // Older deliveries - More than 1 year ago (logistics-1: 4, logistics-2: 3)
  {
    id: 'delivery-33',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[0],
    status: 'delivered',
    origin: { address: 'Farm EEE, Punjab', ...bengaluruLocations.koramangala },
    destination: { address: 'Market FFF, Amritsar', ...bengaluruLocations.hebbal },
    currentLocation: bengaluruLocations.hebbal,
    estimatedArrival: getDaysAgo(400),
    deliveredAt: getDaysAgo(400),
    produceName: 'Mustard',
    quantity: 700,
    sellerName: 'Farmer EEE',
    buyerName: 'Buyer FFF',
    createdAt: getDaysAgo(401),
  },
  {
    id: 'delivery-34',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[1],
    status: 'delivered',
    origin: { address: 'Farm GGG, Haryana', ...bengaluruLocations.electronicCity },
    destination: { address: 'Market HHH, Chandigarh', ...bengaluruLocations.whitefield },
    currentLocation: bengaluruLocations.whitefield,
    estimatedArrival: getDaysAgo(450),
    deliveredAt: getDaysAgo(450),
    produceName: 'Sugarcane',
    quantity: 2500,
    sellerName: 'Farmer GGG',
    buyerName: 'Buyer HHH',
    createdAt: getDaysAgo(451),
  },
  {
    id: 'delivery-35',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[2],
    status: 'delivered',
    origin: { address: 'Farm III, Maharashtra', ...bengaluruLocations.btmLayout },
    destination: { address: 'Market JJJ, Nagpur', ...bengaluruLocations.malleshwaram },
    currentLocation: bengaluruLocations.malleshwaram,
    estimatedArrival: getDaysAgo(500),
    deliveredAt: getDaysAgo(500),
    produceName: 'Grapes',
    quantity: 400,
    sellerName: 'Farmer III',
    buyerName: 'Buyer JJJ',
    createdAt: getDaysAgo(501),
  },
  {
    id: 'delivery-36',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[3],
    status: 'delivered',
    origin: { address: 'Farm KKK, Karnataka', ...bengaluruLocations.yeshwanthpur },
    destination: { address: 'Market LLL, Mysore', ...bengaluruLocations.jayanagar },
    currentLocation: bengaluruLocations.jayanagar,
    estimatedArrival: getDaysAgo(550),
    deliveredAt: getDaysAgo(550),
    produceName: 'Coffee',
    quantity: 300,
    sellerName: 'Farmer KKK',
    buyerName: 'Buyer LLL',
    createdAt: getDaysAgo(551),
  },
  {
    id: 'delivery-37',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[0],
    status: 'delivered',
    origin: { address: 'Farm MMM, Kerala', ...bengaluruLocations.hebbal },
    destination: { address: 'Market NNN, Trivandrum', ...bengaluruLocations.koramangala },
    currentLocation: bengaluruLocations.koramangala,
    estimatedArrival: getDaysAgo(600),
    deliveredAt: getDaysAgo(600),
    produceName: 'Coconut',
    quantity: 800,
    sellerName: 'Farmer MMM',
    buyerName: 'Buyer NNN',
    createdAt: getDaysAgo(601),
  },
  {
    id: 'delivery-38',
    logisticsUserId: 'logistics-1',
    driver: mockDrivers[1],
    status: 'delivered',
    origin: { address: 'Farm OOO, TN', ...bengaluruLocations.whitefield },
    destination: { address: 'Market PPP, Madurai', ...bengaluruLocations.electronicCity },
    currentLocation: bengaluruLocations.electronicCity,
    estimatedArrival: getDaysAgo(650),
    deliveredAt: getDaysAgo(650),
    produceName: 'Tamarind',
    quantity: 550,
    sellerName: 'Farmer OOO',
    buyerName: 'Buyer PPP',
    createdAt: getDaysAgo(651),
  },
  {
    id: 'delivery-39',
    logisticsUserId: 'logistics-2',
    driver: mockDrivers[2],
    status: 'delivered',
    origin: { address: 'Farm QQQ, AP', ...bengaluruLocations.malleshwaram },
    destination: { address: 'Market RRR, Vizag', ...bengaluruLocations.btmLayout },
    currentLocation: bengaluruLocations.btmLayout,
    estimatedArrival: getDaysAgo(700),
    deliveredAt: getDaysAgo(700),
    produceName: 'Millet',
    quantity: 1000,
    sellerName: 'Farmer QQQ',
    buyerName: 'Buyer RRR',
    createdAt: getDaysAgo(701),
  },
];

// Helper function to get completed delivery counts for a logistics user by time period
export const getCompletedDeliveryCounts = (logisticsUserId: string) => {
  const now = new Date();
  const oneMonthAgo = new Date(now);
  oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
  const sixMonthsAgo = new Date(now);
  sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);
  const oneYearAgo = new Date(now);
  oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);

  const completedDeliveries = mockDeliveries.filter(
    d => d.logisticsUserId === logisticsUserId && d.status === 'delivered'
  );

  const lastMonth = completedDeliveries.filter(
    d => d.deliveredAt && d.deliveredAt >= oneMonthAgo
  ).length;

  const lastSixMonths = completedDeliveries.filter(
    d => d.deliveredAt && d.deliveredAt >= sixMonthsAgo
  ).length;

  const lastYear = completedDeliveries.filter(
    d => d.deliveredAt && d.deliveredAt >= oneYearAgo
  ).length;

  const sinceInception = completedDeliveries.length;

  return {
    lastMonth,
    lastSixMonths,
    lastYear,
    sinceInception,
  };
};
